---
title: "Strings in SQL"
author: "Youbeen Shim"
date: "2023-08-22"
output: html_document
---

## String Manipulation and Regular Expressions

The reality is this, the world is messy. Physicists know it too, they always babble on about the second law of thermodynamics or whatever. It’s up to us to create and restore order. 

If everything was perfect in the world, there would be no point to learning these topics. Well, actually, there would be some points, but you get the point. 

Anyways, work remains to be done. I’ll write down some easy examples and make some notes on it that generally covers the use case of that function or concept. Like [before]() it won’t be a full explanation, and I’ll point you to the writers with more experience than me go down that rabbit hole with you. 

Topics today:

* Search and Match  
* Specify and Paste  
* Trim  
* Fill in Blanks  



## Search and Match

#### LIKE vs REGEX

What’s the difference? For one, LIKE is easier. Let's look at [#1527](https://leetcode.com/problems/patients-with-a-condition/):
```
SELECT
    patient_id,
    patient_name,
    conditions
FROM Patients
WHERE conditions LIKE '% DIAB1%' 
OR conditions LIKE 'DIAB1%'
```
I’m using ‘%’ to search for that specific set of characters at the beginning or the end of a string. It’s also possible to leverage ‘_’ to specify the minimum length of a string or the position of a character. For example, the query below find the patients with an ‘r’ in the second character of their name.
```
SELECT
    patient_id,
    patient_name,
    conditions
FROM Patients
WHERE patient_name LIKE '%_r’
```

Regular expressions are more complex and can specify the requirements in greater detail. [#1517](https://leetcode.com/problems/find-users-with-valid-e-mails/) captures the essence of the idea. 
```
SELECT
    user_id,
    name,
    mail
FROM Users
WHERE mail REGEXP '^[A-Za-z]+[A-Za-z0-9\_\.\-]*\@leetcode[.]com$'
```

* \^[a-zA-Z]+: The string must start (\^[]+) with a letter (A-Za-z)  
* [a-zA-z0-9\_\.\-]*: The string can have zero or more ([]*) letter (A-Za-z), number (0-9), or special characters (_   .   -)  
* @leetcode[.]com$: the period (.) must come after @leetcode and end with ($) com  

Obviously this is not a complete explanation nor a comprehensive list, but you can find something more comprehensive [here](https://www.rexegg.com/regex-quickstart.html).

As a side note, from my personal experience, LIKE is typically faster when using single conditions, but REGEXP is faster when dealing with more than one condition. This is unverified and I have done no research on it, but it does seem to reflect the [opinions of the community](https://stackoverflow.com/questions/16646686/mysql-regexp-vs-like) as well.



## Specify and Paste

#### CONCAT()
Pastes two+ strings together. Doesn’t necessarily have to start out as a string, but will be forced as a string as it concatenates.

#### UPPER() and LOWER() 
Changes the strings within the function to be written in upper or lower case.

#### SUBSTRING() or SUBSTR()
Arguments are SUBSTR(string, start, length). Not choosing the length argument will default to returning the whole string from the start onwards. 

[#1667](https://leetcode.com/problems/fix-names-in-a-table/)
```
SELECT
    user_id, 
    CONCAT(UPPER(SUBSTRING(name, 1, 1)),LOWER(SUBSTRING(name, 2))) AS name
FROM Users
ORDER BY user_id

– LOWER(SUBSTR(name, 2, length(name)-1)) would be equivalent
```

It could also be something like this.

#### LEFT() AND RIGHT()
Returns the number of characters specified starting from the leftmost or the rightmost position. Below we use left and right instead of using substring twice. More for demonstration purposes though.
```
SELECT 
user_id, 
CONCAT(UPPER(LEFT(name, 1)), LOWER(RIGHT(name, LENGTH(name)-1))) AS name
FROM Users
ORDER BY user_id
```



## Trim

#### TRIM()
Trims (could not think of any other word that described that action better) any character specified within the quote from the beginning, end, or both. 

```
Select
	Name,
	customer_Id,
	Address, 
	TRIM(BOTH ‘[]’ FROM zip_code)
FROM clientAddress
```



## Fill in Blanks

#### COALESCE()
Fills in null values with a value specified.

```
Select
	Name,
	customer_Id,
	Address, 
	COALESCE(marriage_status, ‘No Info’)
FROM Clients
```

