baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "A website built with blogdown, Hugo, and random sparks of inspiration."
  footer: "&copy; [Youbeen Shim](https://www.instagram.com/youbeanz/) 2021 -- {Year} | [Github](https://github.com/youbeen-shim) | [LinkedIn](https://www.linkedin.com/in/youbeen-shim/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
